version: "3.5"

services:

  nginx:
    container_name: dev_pledge_nginx
    image: nginx:1.13.7
    volumes:
      - ./dev.config:/etc/nginx/conf.d:cached
      - ./dev.ssl:/etc/nginx/ssl:cached
    ports:
      - 80:80
      - 443:443
      - 9501:9501
    networks:
      - sentry_network
      - api_network
      - ui_network
      - feed_network


networks:
  sentry_network:
    external:
      name: global_sentry

  api_network:
    external:
      name: devpledge_api

  ui_network:
    external:
      name: devpledge_ui

  feed_network:
    external:
      name: devpledge_feed